version: '3.3'
services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      TZ: $TZ
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE_DBNAME}
      MONGODB_DATA_DIR: ${MONGODB_DATA_DIR}
      MONDODB_LOG_DIR: /dev/null
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ./mongo/data:/data/db
